package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Agencia generated by hbm2java
 */
public class Agencia  implements java.io.Serializable {


     private int id;
     private String direccion;
     private String titular;
     private Integer telefono;
     private Integer fax;
     private Integer zona;
     private Set vendedoreses = new HashSet(0);
     private Set inmuebles = new HashSet(0);

    public Agencia() {
    }

	
    public Agencia(int id) {
        this.id = id;
    }
    public Agencia(int id, String direccion, String titular, Integer telefono, Integer fax, Integer zona, Set vendedoreses, Set inmuebles) {
       this.id = id;
       this.direccion = direccion;
       this.titular = titular;
       this.telefono = telefono;
       this.fax = fax;
       this.zona = zona;
       this.vendedoreses = vendedoreses;
       this.inmuebles = inmuebles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTitular() {
        return this.titular;
    }
    
    public void setTitular(String titular) {
        this.titular = titular;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getFax() {
        return this.fax;
    }
    
    public void setFax(Integer fax) {
        this.fax = fax;
    }
    public Integer getZona() {
        return this.zona;
    }
    
    public void setZona(Integer zona) {
        this.zona = zona;
    }
    public Set getVendedoreses() {
        return this.vendedoreses;
    }
    
    public void setVendedoreses(Set vendedoreses) {
        this.vendedoreses = vendedoreses;
    }
    public Set getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set inmuebles) {
        this.inmuebles = inmuebles;
    }




}


