package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alquilado generated by hbm2java
 */
public class Alquilado  implements java.io.Serializable {


     private int id;
     private Double precio;
     private Double fianza;
     private Set inmuebles = new HashSet(0);

    public Alquilado() {
    }

	
    public Alquilado(int id) {
        this.id = id;
    }
    public Alquilado(int id, Double precio, Double fianza, Set inmuebles) {
       this.id = id;
       this.precio = precio;
       this.fianza = fianza;
       this.inmuebles = inmuebles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Double getFianza() {
        return this.fianza;
    }
    
    public void setFianza(Double fianza) {
        this.fianza = fianza;
    }
    public Set getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set inmuebles) {
        this.inmuebles = inmuebles;
    }




}


