package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private Set vendedoreses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String dni) {
        this.dni = dni;
    }
    public Clientes(String dni, String nombre, Set vendedoreses) {
       this.dni = dni;
       this.nombre = nombre;
       this.vendedoreses = vendedoreses;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVendedoreses() {
        return this.vendedoreses;
    }
    
    public void setVendedoreses(Set vendedoreses) {
        this.vendedoreses = vendedoreses;
    }




}


