package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private int codigo;
     private Agencia agencia;
     private Alquilado alquilado;
     private Vendido vendido;
     private Set pisos = new HashSet(0);
     private Set locals = new HashSet(0);

    public Inmueble() {
    }

	
    public Inmueble(int codigo) {
        this.codigo = codigo;
    }
    public Inmueble(int codigo, Agencia agencia, Alquilado alquilado, Vendido vendido, Set pisos, Set locals) {
       this.codigo = codigo;
       this.agencia = agencia;
       this.alquilado = alquilado;
       this.vendido = vendido;
       this.pisos = pisos;
       this.locals = locals;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Agencia getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }
    public Alquilado getAlquilado() {
        return this.alquilado;
    }
    
    public void setAlquilado(Alquilado alquilado) {
        this.alquilado = alquilado;
    }
    public Vendido getVendido() {
        return this.vendido;
    }
    
    public void setVendido(Vendido vendido) {
        this.vendido = vendido;
    }
    public Set getPisos() {
        return this.pisos;
    }
    
    public void setPisos(Set pisos) {
        this.pisos = pisos;
    }
    public Set getLocals() {
        return this.locals;
    }
    
    public void setLocals(Set locals) {
        this.locals = locals;
    }




}


