package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1



/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private int id;
     private Inmueble inmueble;
     private String licenciaApertura;

    public Local() {
    }

	
    public Local(int id) {
        this.id = id;
    }
    public Local(int id, Inmueble inmueble, String licenciaApertura) {
       this.id = id;
       this.inmueble = inmueble;
       this.licenciaApertura = licenciaApertura;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    public String getLicenciaApertura() {
        return this.licenciaApertura;
    }
    
    public void setLicenciaApertura(String licenciaApertura) {
        this.licenciaApertura = licenciaApertura;
    }




}


