package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedores generated by hbm2java
 */
public class Vendedores  implements java.io.Serializable {


     private VendedoresId id;
     private Agencia agencia;
     private String nombre;
     private Set clienteses = new HashSet(0);

    public Vendedores() {
    }

	
    public Vendedores(VendedoresId id, Agencia agencia) {
        this.id = id;
        this.agencia = agencia;
    }
    public Vendedores(VendedoresId id, Agencia agencia, String nombre, Set clienteses) {
       this.id = id;
       this.agencia = agencia;
       this.nombre = nombre;
       this.clienteses = clienteses;
    }
   
    public VendedoresId getId() {
        return this.id;
    }
    
    public void setId(VendedoresId id) {
        this.id = id;
    }
    public Agencia getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


