package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1



/**
 * VendedoresId generated by hbm2java
 */
public class VendedoresId  implements java.io.Serializable {


     private String dni;
     private int idAgencia;

    public VendedoresId() {
    }

    public VendedoresId(String dni, int idAgencia) {
       this.dni = dni;
       this.idAgencia = idAgencia;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getIdAgencia() {
        return this.idAgencia;
    }
    
    public void setIdAgencia(int idAgencia) {
        this.idAgencia = idAgencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendedoresId) ) return false;
		 VendedoresId castOther = ( VendedoresId ) other; 
         
		 return ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) )
 && (this.getIdAgencia()==castOther.getIdAgencia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         result = 37 * result + this.getIdAgencia();
         return result;
   }   


}


