package Hibernate_mapping_files;
// Generated 18-nov-2014 20:09:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendido generated by hbm2java
 */
public class Vendido  implements java.io.Serializable {


     private int id;
     private Double precio;
     private Boolean hipotecado;
     private Set inmuebles = new HashSet(0);

    public Vendido() {
    }

	
    public Vendido(int id) {
        this.id = id;
    }
    public Vendido(int id, Double precio, Boolean hipotecado, Set inmuebles) {
       this.id = id;
       this.precio = precio;
       this.hipotecado = hipotecado;
       this.inmuebles = inmuebles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Boolean getHipotecado() {
        return this.hipotecado;
    }
    
    public void setHipotecado(Boolean hipotecado) {
        this.hipotecado = hipotecado;
    }
    public Set getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set inmuebles) {
        this.inmuebles = inmuebles;
    }




}


